name: pre-build
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
  #schedule:
  #  - cron: "0 */3 * * *" # UTC

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.0.3

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('setup.R') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          install.packages("remotes")
          cmds <- remotes::system_requirements("ubuntu", "20.04")
          for (cmd in cmds) {
            system(paste("sudo", cmd))
          }
          system("sudo apt-get install -y default-jre")
        shell: Rscript {0}
        
      - name: Install R packages
        run: Rscript setup.R
       
      - name: pre-build actions
        run: |
          make data
          make document
          make test
          git diff
        #MAKE_ENV=GITHUB_ACTIONS make ga-commit

      #- name: Push changes
      #  #if: ${{ env.NUM_UPDATED_FILES > 0 }} will this be error?
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}
